@width = 52
@height = 52
@levels =
    0: '
        --------------------------
        -0-----------0-----------0
        --oo--oo--oo--oo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo--ooXXoo--oo--oo--
        --oo--oo--ooXXoo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo----------oo--oo--
        --oo--oo----------oo--oo--
        ----------oo--oo----------
        ----------oo--oo----------
        oo--oooo----------oooo--oo
        XX--oooo----------oooo--XX
        ----------oo--oo----------
        ----------oooooo----------
        --oo--oo--oooooo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo--oo--oo--oo--oo--
        --oo--oo----------oo--oo--
        --oo--oo----------oo--oo--
        --oo--oo---oooo---oo--oo--
        -----------o--o-----------
        ---------1-o-@o--2--------'
    1: '
        ------XX------XX----------
        -0----XX-----0XX---------0
        --oo--XX------oo--oo--oo--
        --oo--XX------oo--oo--oo--
        --oo--------oooo--ooXXoo--
        --oo--------oooo--ooXXoo--
        ------oo----------XX------
        ------oo----------XX------
        ~~----oo----XX----oo~~ooXX
        ~~----oo----XX----oo~~ooXX
        ~~~~------oo----XX--~~----
        ~~~~------oo----XX--~~----
        --oooooo~~~~~~XX----~~oo--
        --oooooo~~~~~~XX----~~oo--
        ------XX~~oo--oo--oo--oo--
        ------XX~~oo--oo--oo--oo--
        XXoo--XX--oo--oo------oo--
        XXoo--XX--oo--oo------oo--
        --oo--oo--oooooo--ooXXoo--
        --oo--oo--oooooo--ooXXoo--
        --oo--oo--oooooo----------
        --oo--oo--oooooo----------
        --oo--------------oo--oo--
        --oo-------oooo---oo--oo--
        --oo--oo---o--o---oooooo--
        --oo--oo-1-o-@o--2oooooo--'
    2: '
        ........oo......oo........
        .0......oo...0..oo.......0
        ..~~~~~~oo................
        ..~~~~~~oo..........XXXXXX
        oo~~~~~~..................
        oo~~~~~~..................
        ~~~~~~~~......oo..ooooooo.
        ~~~~~~~~......oo..ooooooo.
        ~~~~~~~~oooooooo..oo...o..
        ~~~~~~~~oooooo....oo...o..
        ~~~~~~~~....oo.........o..
        ~~~~~~~~....oo.........o..
        ..~~........XXXXXX....~~..
        ..~~........XXXXXX....~~..
        ..................~~~~~~~~
        ..oo..oo..........~~~~~~~~
        ooo..oooo..ooooooo~~~~~~~~
        ooo..oooo..o......~~~~~~~~
        ..........oo......~~~~~~~~
        ..........oo..oooo~~~~~~~~
        oo....X.......oooo~~~~~~..
        oo....X...........~~~~~~..
        oooo..X...........~~~~~~..
        oooo..X....oooo...~~~~~~..
        XXoooo.....o..o...oo......
        XXoooo...1.o.@o..2oo......'
    3: '
        --~~~~----------------~~--
        -0~~~~-------0--------~~-0
        ~~~~------oooo----------~~
        ~~~~----oooooooooo------~~
        ~~-----ooooooooooooo----XX
        ~~-----ooooooooooooooo----
        XX----ooooooooooooooooo---
        ------ooooooooooooooooo---
        -----ooo------oooooo--o---
        -----o----------oooo--o---
        ==---o--X---X---ooo-------
        ==---o--X---X---ooo-------
        ----oo----------ooo---====
        ----oo--oooo----ooo---====
        ----oooooooooooooooo------
        ----oooooooooooooooo------
        ---oooooooooooooooooo-----
        ---oooooooooooooooooo-----
        --oooooooooooooooooooo----
        ------oooooooooooo--------
        --oooo--oooooooo--oooo--~~
        --oooooo--oooo--oooooo--~~
        ~~--oooo--------oooo--~~~~
        ~~---------oooo-------~~~~
        XX~~-------o--o-----~~~~XX
        XX~~-----1-o-@o--2--~~~~XX'
    20: '
        ------==--oo----oo--oo----
        -0----==--oo-0--oo--oo---0
        ----------------oo--XX----
        ----------------oo--XX----
        ------==----XX--oo--oo----
        ------==--ooXX--oo--oo----
        XX--oo==--XX----oo--oo----
        ----oo==--XX--oo----oo----
        ----oo==------oo----------
        ----oo==------oo----------
        oo--oo====--========----oo
        oo--oo====--========----oo
        --------------~~--==--XXXX
        ------oo------~~--==------
        oooo-ooo--XX~~~~~~==------
        oooo-ooo--XX~~~~~~==--oooo
        oo---o----oo~~~~~~==--oo--
        -----o----oo~~~~~~==--oo--
        ----------oo--~~--==--~~--
        --XX------oo--~~--==--~~--
        --oo------oooooo----~~~~~~
        --oo--XX------------~~~~~~
        --oo--oo----------==~~~~~~
        --oo--oo---oooo---==~~~~~~
        -----------o--o---==--~~--
        ---------1-o-@o--2==--~~--'
